### PR TITLE
expose NetcodeSocket

### LINKED ISSUE #10: Expose NetcodeSocket
Similar to #7

I am working on Python bindings for this library, but typing a `Client` requires access to `NetcodeSocket`.

image

### PR DESCRIPTION
**Pull request by benjamin-kirkbride**
Resolves #10

### CODE REVIEW

**Review by benny-n — COMMENTED** [review]
Thanks for the PR!
Now that we expose `NetcodeSocket`, let's make sure it's hard to misuse by encapsulating the inner `UdpSocket`:
```diff
- pub struct NetcodeSocket(pub UdpSocket);
+ pub struct NetcodeSocket(UdpSocket);
```
Other than that, LGTM.
I'll make sure to include this in `v1.4.0`!

**Comment by benjamin-kirkbride** [comment]
I actually made a mistake with it I think, sorry I don't really know rust. I exposed it from the client module, not the socket module

**Comment by benjamin-kirkbride** [comment]
but I fixed that on the pr?

**Comment by benjamin-kirkbride** [comment]
just make sure you test it before you merge :sweat_smile:

**Comment by benny-n** [comment]
@benjamin-kirkbride No worries, that's what CI is for 😅
I am also okay with merging it as is and making the change on my end.

**Comment by benjamin-kirkbride** [comment]
Thanks!!

**Pull request merged**
